### ISSUE TITLE
"JSONSchema" canonical "$ref" incorrect

### ISSUE THREAD

**Issue by ricktaylor** [open-rpc/meta-schema#323]
The "$ref" for the "/definitions/JsonSchema" object currently refers "https://raw.githubusercontent.com/json-schema-tools/meta-schema/1.5.9/src/schema.json" (and I noticed you have recently had to update it to track updates in json-schema-tools).

Surely this "$ref" should be pointing to "https://meta.json-schema.tools/" as that is the base "$id" of the underlying schema, as specified by the top-level "$schema" property - the exact same schema you now want to reference?

**Comment by BelfordZ** [comment]
Hey @ricktaylor Thanks for the issue. You are indeed correct in your assumption - $ref should be to the `meta.json-schema.tools` url. The main (and after a few fixes I think now the only) reason we haven't switched the url:

https://meta.json-schema.tools/ needs versioned url variant, and at the moment, only the latest is being released. The code to do this will be very similar to what is in open-rpc/spec's build scripts (spec.open-rpc.org/${version} is working already) - the main difference being that the input/output is a json schema instead of markdown

I'll do what I can to prio the work and get versioned urls together. 

Also just for information sake - the current meta schema @ json-schema-tools is a copy of Draft-7 with the addition of `title` on the metaschema and all its subschemas. This is done to yeild [pretty typing names](https://github.com/json-schema-tools/meta-schema/blob/master/json_schema.go#L17) instead of generated ones (I dont have any examples, but you can make one easily via https://json-schema.tools ).
