### ISSUE TITLE
Why not use "http://json-schema.org/draft-07/schema#" instead of "https://meta.json-schema.tools/#"

### ISSUE THREAD

**Issue by ricktaylor** [open-rpc/meta-schema#324]
As a tooling author, having to support yet another JSONSchema variant is frankly a PITA.

http://json-schema.org/draft-07/schema# seems to be exactly what you want to be tracking for the meta-schema, unless you want to move to the less mature "draft 8".

Why an alternative JSONSchema schema?

**Comment by BelfordZ** [comment]
> the current meta schema @ json-schema-tools is a copy of Draft-7 with the addition of title on the metaschema and all its subschemas. This is done to yeild pretty typing names instead of generated ones (I dont have any examples, but you can make one easily via https://json-schema.tools ).

exceprt from https://github.com/open-rpc/meta-schema/issues/323#issuecomment-724987253

here are a few reasons: 
1. The main reason for this is so that we could add titles to the meta schema, as well as in the near future, description fields (which editors configured to use this meta schema will happily make use of).
1. While all the tooling supports the regular json-schema.org draft 7 schema, the addition of titles to the schema yeilds a significant usability improvement. 
1. Much of the purpose of json-schema-tools org is to have more control an uniformity over json schema tooling. The goal is to provide a comprehensive tooling stack around the JSON schema specification. Having said that, I consider the meta-schema to be part of the tooling stack, and only a codified reflection of the specification.
1. Lack of ssl on returned json-schema.org/draft-07 meta schema's urls. (example, $schema is http url). meta.json-schema.tools always returns the $schema with https. http->https redirect was considered, but it seemed okay to leave it for compatibility.
1. Default response header `Content-Type: application/octet-stream` means browsers default to downloading the json. Sad.

I understand that in some cases its very inconvenient. Many tools/validators have hardcoded meta-schemas for given $schema values. They also likely handle the afforementioned http(s) issue. Having to add another meta schema is certainly a drag, and the goal here was to provide the same meta schema, but with improvements. If for what ever reason you are unable to use it as a drop in replacement, swapping out the $ref for your own application will work without issue (as mentioned, they are validator-equivalent meta-schemas).

**Comment by ricktaylor** [comment]
Thanks @BelfordZ - great explanation, all good reasons.

Since raising the issue, I've added support to my for https://json-schema.tools so I can make progress - feel free to close the issue.

Keep up the good work - OpenRPC is good technology.

**Comment by BelfordZ** [comment]
Thank you for the issue! Feel free to be liberal in opening them!
